### ISSUE TITLE
numeric sorting fails on negative values

### ISSUE THREAD

**Issue by wizfromoz** [thi747/tablejs#2]
Hi,
just an observation: your code in table.js, line 56:

val = parseFloat(val.replace(/^[^\d\.]*([\d., ]+).*/g,"$1").replace(new RegExp("[^\\\d"+separator+"]","g"),'').replace(/,/,'.')) || 0;

basically ignores the potential presence of sign character (-), so the returned value, effectively, is like abs(val). If you put in instead:

val = parseFloat(val.replace(/^[^-\d\.]*(-?[\d., ]+).*/g,"$1").replace(new RegExp("[^-\\\d"+separator+"]","g"),'').replace(/,/,'.')) || 0;

then it will capture the sign character and the numeric sorting on the column would be correct

**Comment by ArkadiuszBogonos** [comment]
Hello, your solution that fixes sorting negative values breaks sorting integer numbers and sorting decimals with a comma (at least on firefox). 

Here is improved solution that works with both negative values and integers / decimals with comma

val = parseFloat(val.replace(/^[^-\d\.]*(-?[\d., ]+).*/g,"$1").replace(new RegExp("[^-\\\d"+separator+"]","g"),'').replace(/,/,'.')) || 0;

**Comment by thi747** [comment]
Thank you guys

**Comment by thi747** [comment]
Thank you guys, the fix was added.
